Revert "Fix pgpool child process segfault when ALWAYS_MASTER is on."
This reverts commit 9022ff842fb5dbbe06e2f2f4cf38fadf47b592da.

With the commit, write queries are always sent to node 0 even if the
primary node is not 0 because PRIMARY_NODE_ID macro returns
REAL_MASTER_NODE_ID, which is usually 0. Thus write queries are failed
with:
ERROR:  cannot execute INSERT in a read-only transaction