Fix: The INSERT statment did not correspond to the parser of postgresql 8.3      that pgpool-II 2.0 had.      Therefore, the following errors occur if INSERT is done in a parallel mode
     ERROR: pgpool2 sql restriction
     DETAIL: cannot use SElectStmt in InserStmt