Fix regression test 028.watchdog_enable_consensus_with_half_of_the_votes to not fail.
It seems pcp_watchdog_info fails because:
ERROR: connection to socket "/tmp/.s.PGSQL.50001" failed with error "No such file or directory"

Fix could be trying to wait for pcp_watchdog_info available. See if this fixes the issue.