Test: stabilize 032.dml_adaptive_loadbalance
Occasionally the test failed due to:
ERROR:  relation "t2" does not exist
LINE 1: SELECT i, 'QUERY ID T1-1' FROM t2;

It seems the cause is that newly created table t2 takes sometime to
get replicated to standby. So insert "sleep 1" after the table
creation.

Backpatch-through: v4.2