snprintf: Add math.h to ensure isnan and isinf are defined
When building for 32-bit arm arch, compilation fails with the following error:
| snprintf.c: In function 'fmtfloat':
| snprintf.c:1232:13: error: implicit declaration of function 'isnan' [-Wimplicit-function-declaration]
|  1232 |         if (isnan(value))
|       |             ^~~~~
| snprintf.c:50:1: note: include '<math.h>' or provide a declaration of 'isnan'
|    49 | #include "postgresql/server/port.h"
|   +++ |+#include <math.h>
|    50 |
| snprintf.c:1254:21: error: implicit declaration of function 'isinf' [-Wimplicit-function-declaration]
|  1254 |                 if (isinf(value))
|       |                     ^~~~~
| snprintf.c:1254:21: note: include '<math.h>' or provide a declaration of 'isinf'

To avoid the error, add math.h to snprintf.c.

Signed-off-by: Gyorgy Sarvari <skandigraun@gmail.com>