Fix compiler error.
The commit 8c1795792 "Fix premature Sync during extended-query
pipelines" introduced a compile error in Rocky Linux 8.

protocol/pool_proto_modules.c: In function 'ProcessFrontendResponse':
protocol/pool_proto_modules.c:3165:4: error: a label can only be part of a statement and a declaration is not a statement
    bool  defer_primary_sync;

Author: Tatsuo Ishii <ishii@postgresql.org>
Backpatch-through: v4.3